name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Get SSH known hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan github.com > ~/.ssh/known_hosts

      # - name: Read known_hosts into env
      #   id: knownhosts
      #   run: echo "KNOWN_HOSTS=$(cat ~/.ssh/known_hosts)" >> $GITHUB_ENV

      - name: Setup SSH key with shimataro
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host github.com-alonsorodriv
              HostName github.com
              User git
              IdentityFile ~/.ssh/id_rsa

      # - name: Setup SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     echo -e "Host github.com-alonsorodriv\n  HostName github.com\n  User git\n  IdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set git config
        run: |
          git config --global user.name "AlonsoRodRiv"
          git config --global user.email "rr14112@ues.edu.sv"

      - name: Deploy to Github pages
        run: npx ng deploy --repo=git@github.com-alonsorodriv:AlonsoRodRiv/productos_frontend.git --name="AlonsoRodRiv" --base-href=/productos_frontend/

      # - name: Deploy to Github pages
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN_CD }}
      #   run: npm run deploy -- --repo=https://AlonsoRodRiv:${{ env.GITHUB_TOKEN }}@github.com/AlonsoRodRiv/productos_frontend.git --name="AlonsoRodRiv"
