name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Github pages
        run: npx ng deploy --repo=https://github.com/AlonsoRodRiv/productos_frontend.git --name="AlonsoRodRiv" --base-href=/productos_frontend/ --no-silent
        env:
          GH_TOKEN: ${{ secrets.TOKEN_CD }}
